## import numpy library

In [1]:
import numpy as np

### Basic

In [9]:
a = np.array([1,2,3],dtype='int16')

In [10]:
print(a)

[1 2 3]


In [19]:
b = np.array([[1,2,3.0,4],[5,6,7,8]])

In [20]:
print(b)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


In [21]:
# get Dimension
print(a.ndim)
print(b.ndim)

1
2


In [22]:
# Get shape
print(a.shape)
print(b.shape)

(3,)
(2, 4)


In [23]:
# get type

print(a.dtype)
print(b.dtype)

int16
float64


In [24]:
# get size
print(a.itemsize)
print(b.itemsize)

2
8


### Accessing/Changing specific element

In [26]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [27]:
# get specific element [r,c]
a[1,3]

11

In [28]:
a[1,-4]

11

In [30]:
# get specific row
print(a[0,:])

[1 2 3 4 5 6 7]


In [31]:
# get specific column
print(a[:,3])

[ 4 11]


In [39]:
# getting a little more fancy [startindex:endindex:stepsize]
print(a[0, 1:6:2])
print(a[0, 1:6:1])
print(a[0, 1:-2:1])
print(a[0, 1:-2:2])

[2 4 6]
[2 3 4 5 6]
[2 3 4 5]
[2 4]


In [41]:
a[1,5] = 20

In [42]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 20, 14]])

In [45]:
a[:,2]=25
a

array([[ 1,  2, 25,  4,  5,  6,  7],
       [ 8,  9, 25, 11, 12, 20, 14]])

In [48]:
a[:,2]=[45,50]
a

array([[ 1,  2, 45,  4,  5,  6,  7],
       [ 8,  9, 50, 11, 12, 20, 14]])

### 3D example

In [53]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [54]:
# get specific element
b[1,0,1]

6

In [55]:
b[:,0,1]

array([2, 6])

In [56]:
# replace
b[0,1,1] =33

In [57]:
b

array([[[ 1,  2],
        [ 3, 33]],

       [[ 5,  6],
        [ 7,  8]]])

In [59]:
b[0,1,:]  = [11,22]

In [60]:
b

array([[[ 1,  2],
        [11, 22]],

       [[ 5,  6],
        [ 7,  8]]])

### Initializing Different Type of Arrays

In [61]:
# all zero matrix
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [63]:
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [64]:
# all one metrix
np.ones(5)

array([1., 1., 1., 1., 1.])

In [66]:
np.ones((2,3), dtype='int16')

array([[1, 1, 1],
       [1, 1, 1]], dtype=int16)

In [67]:
# any other numbers
np.full((2,3),33)

array([[33, 33, 33],
       [33, 33, 33]])

In [68]:
np.full((2,3),33,dtype='float32')

array([[33., 33., 33.],
       [33., 33., 33.]], dtype=float32)

In [69]:
# any other numbers (full_likes)
np.full_like(b,99)

array([[[99, 99],
        [99, 99]],

       [[99, 99],
        [99, 99]]])

In [70]:
np.full(b.shape,99)

array([[[99, 99],
        [99, 99]],

       [[99, 99],
        [99, 99]]])

In [73]:
# Random decimal numbers
np.random.rand(4,3)

array([[0.15967967, 0.67461381, 0.77185915],
       [0.07894396, 0.08004074, 0.74571486],
       [0.24272522, 0.06438806, 0.10262349],
       [0.77509996, 0.30296602, 0.71279156]])

In [74]:
np.random.rand(4,3)

array([[0.37578106, 0.77842032, 0.01482113],
       [0.42208979, 0.35245019, 0.4248214 ],
       [0.22880611, 0.10651804, 0.9128384 ],
       [0.71227811, 0.00125668, 0.60625576]])

In [75]:
np.random.rand(4,3,3)

array([[[0.99083437, 0.14759322, 0.11786467],
        [0.06407605, 0.7199537 , 0.93346629],
        [0.99381345, 0.55532904, 0.93355137]],

       [[0.11431629, 0.70298882, 0.14265243],
        [0.67239048, 0.84090761, 0.00695033],
        [0.26512504, 0.39982602, 0.02848762]],

       [[0.22155788, 0.88659326, 0.17138821],
        [0.01770189, 0.68921065, 0.74081647],
        [0.73858676, 0.07452947, 0.91655449]],

       [[0.86234956, 0.1145945 , 0.36560806],
        [0.57249855, 0.59170665, 0.87134698],
        [0.56802795, 0.34522369, 0.99415266]]])

In [76]:
np.random.random_sample(b.shape)

array([[[0.81867472, 0.11658467],
        [0.03727575, 0.25977418]],

       [[0.5175053 , 0.48384581],
        [0.65173209, 0.41583568]]])

In [79]:
# random integer value
np.random.randint(5,size=(3,4))

array([[1, 2, 1, 3],
       [4, 2, 3, 1],
       [2, 3, 0, 0]])

In [80]:
np.random.randint(5,size=(3,4))

array([[2, 3, 2, 0],
       [4, 4, 3, 2],
       [0, 3, 3, 4]])

In [81]:
np.random.randint(3,5,size=(3,4))

array([[3, 4, 3, 4],
       [3, 3, 3, 4],
       [3, 3, 4, 4]])

In [83]:
# identuty matrix
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [86]:
# repeat an array
arr = np.array([[1,2,3]])
r = np.repeat(arr,4,axis=0)
print(r)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


In [90]:
# task
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1]=9
print(z)
output[1:4,1:4]=z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


### copy array

In [93]:
a= np.array([1,2,3])
b=a
b[0]=100
print(b)
print(a)

[100   2   3]
[100   2   3]


In [94]:
a= np.array([1,2,3])
b=a.copy()
b[0]=100
print(b)
print(a)

[100   2   3]
[1 2 3]


### Mathematics

In [95]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [97]:
print(a+3)

[4 5 6 7]


In [98]:
print(a*3)

[ 3  6  9 12]


In [100]:
print(a/3)

[1 2 0 1]


In [102]:
print(a%3)

[1 2 0 1]


In [103]:
b = np.array([5,6,7,8])

In [104]:
a+b

array([ 6,  8, 10, 12])

In [105]:
a**b

array([    1,    64,  2187, 65536], dtype=int32)

In [106]:
# sin , cos,tan values
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [107]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [108]:
np.tan(a)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128])

### Linear Algebra

In [111]:
a = np.ones((2,3))
print(a)

b = np.full((3,2),2)
print(b)


[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [112]:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [114]:
# find the deteminat
c = np.identity(3)
print(c)
np.linalg.det(c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


1.0

### Statistics

In [116]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [117]:
np.min(a)

1

In [118]:
np.max(a)

6

In [120]:
np.sum(a,axis = 0)

array([5, 7, 9])